---
- name: Deploy Dockerized Store
  hosts: all
  become: yes
  tasks:
    - name: Update apt and install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Login to DockerHub
      shell: "echo {{ docker_password }} | docker login -u {{ docker_user }} --password-stdin"
      # We use no_log to keep your password out of the GitHub Action logs
      no_log: true

    - name: Pull and Run App
      shell: |
        docker pull {{ docker_user }}/ramu-store:latest
        docker stop ramu-app || true
        docker rm ramu-app || true
        docker run -d --name ramu-app -p 80:80 {{ docker_user }}/ramu-store:latest